{
 "title": "Daily | Off-Grid Monitoring",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "downsampler": "mean",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "B", "reducer": "sum", "type": "reduce" }
   ]
  },
  {
   "title": "Total Grid Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT eacDischarToday FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Battery Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT ebatDischarToday FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Direct Solar Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(eacDischarToday) FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "query": "SELECT last(ebatDischarToday) FROM \"JNK0CA30GE\" WHERE $timeFilter"
    },
    {
     "downsampler": "mean",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "D", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$E-(($B+$C)*1000)", "type": "math" }
   ]
  },
  {
   "title": "Charged By Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(eacDischarToday) FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "query": "SELECT last(ebatDischarToday) FROM \"JNK0CA30GE\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(epvtoday) FROM \"JNK0CA30GE\" WHERE $timeFilter"
    },
    {
     "downsampler": "mean",
     "expression": "Usage",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "UsageRe", "reducer": "sum", "type": "reduce" },
    { "expression": "$Grid*1000", "type": "math" },
    { "expression": "$Bat*1000", "type": "math" },
    { "expression": "$PV*1000", "type": "math" },
    {
     "expression": "$SolarProduction - ($PowerUsage-($GridUsage + $BatteryUsage))",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT epvtoday FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT op_watt FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Grid",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT AC_InWatt FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT BatWatt FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT ppv1 FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current SOC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT \"batterySoc\" AS \"SOC\" FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT invtemp AS \"Temp\" FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT op_watt AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT ppv1 AS \"PV\" FROM \"JNK0CA30GE\" WHERE $timeFilter"
    },
    {
     "query": "SELECT BatWatt AS \"Battery\" FROM \"JNK0CA30GE\" WHERE $timeFilter"
    },
    {
     "query": "SELECT AC_InWatt AS \"Grid\" FROM \"JNK0CA30GE\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Hourly Power Consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(1h) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT ppv1 AS \"PV\" FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT batterySoc AS \"SOC\" FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Grid Usage History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT eacDischarToday FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Battery Usage History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT ebatDischarToday FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT bat_Volt AS \"Battery Voltage\" FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT loadpercent FROM \"JNK0CA30GE\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT invtemp AS \"Temp\" FROM \"JNK0CA30GE\"",
     "select": [
      [
       { "params": [ "AC_InVA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}