{
 "title": "Monthly | Off-Grid Monitoring",
 "time": { "from": "2022-12-13T18:30:00.000Z", "to": "2023-01-14T18:29:59.000Z" },
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "downsampler": "mean",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "B", "reducer": "sum", "type": "reduce" }
   ]
  },
  {
   "title": "Grid usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(eacDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "A", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Battery usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(ebatDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "A", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Direct Solar Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "downsampler": "mean",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "B", "reducer": "sum", "type": "reduce" },
    {
     "query": "SELECT max(eacDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "C", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "query": "SELECT max(ebatDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "D", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "abs($Bat_usage) +  abs($Grid_usage)",
     "type": "math"
    },
    {
     "expression": "abs($Total_usage/1000)-abs($Bat_n_grid)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Solar Charging",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"Usage\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(30m) fill(previous)",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "downsampler": "mean",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1h"
    },
    { "expression": "B", "reducer": "sum", "type": "reduce" },
    {
     "query": "SELECT max(eacDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "C", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "query": "SELECT max(ebatDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "D", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "abs($Bat_usage) +  abs($Grid_usage)",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(epvtoday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "E", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "abs($Solar_generation) - (abs($Total_usage/1000)-abs($Bat_n_grid))",
     "type": "math"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(epvtoday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    },
    { "expression": "A", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "JNK0CA30GE",
     "query": "SELECT mean(\"op_watt\") AS \"AHU\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(1h) fill(previous) ",
     "select": [
      [
       { "params": [ "op_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "downsampler": "sum",
     "expression": "Average Hourly Usage",
     "type": "resample",
     "upsampler": "fillna",
     "window": "24h"
    }
   ]
  },
  {
   "title": "Grid usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(eacDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    }
   ]
  },
  {
   "title": "Battery usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(ebatDischarToday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT max(epvtoday) AS \"Total\" FROM \"JNK0CA30GE\" WHERE $timeFilter GROUP BY time(24h,-29h)"
    }
   ]
  }
 ]
}